name = "monoid.space"

[lib]
name = "MonoidSpace"
srcDir = "."
defaultTarget = true

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "aesop"
git = "https://github.com/JLimperg/aesop"

[[require]]
name = "batteries"
scope = "leanprover-community"
