name:                monoid-space
version:             0.1.0.0
github:              "ixaxaar/monoid.space/"
license:             "Apache2"
author:              "Russi Chatterjee"
maintainer:          "russi@monoid.space"
copyright:           "2019 Russi"

extra-source-files:
- README.md

dependencies:
- base             >= 4.7 && < 5
- EdisonCore       == 1.3.2.1
- EdisonAPI        == 1.3.1
- data-hash        == 0.2.0.1
- equivalence      == 0.3.4
- STMonadTrans     == 0.4.4
- geniplate-mirror == 0.7.6
- Agda             == 2.6.0.1
