name:                monoid-space
version:             0.1.0.0
github:              "ixaxaar/monoid.space/"
license:             "Apache2"
author:              "Russi Chatterjee"
maintainer:          "russi@monoid.space"
copyright:           "2019 Russi"

extra-source-files:
- README.md

dependencies:
- base             >= 4.7 && < 5
- Agda             == 2.6.0.1
